### ISSUE TITLE
Request: pre-built installer

### ISSUE THREAD

**Issue by nocnokneo** [shanselman/PanTiltZoomSystem#1]
Sweet project - just what I'm looking for! Do you have plans to make pre-build installers available? Or just build instructions so that I can build it myself with VS Express. (My particular need is for a 32-bit Windows 7 and 32-bit Windows XP build) Thanks!

**Comment by shanselman** [comment]
I need some volunteers but yes, I could make some installers. You have this camera? You just want the PTZ stuff or the AutoAnswerKiosk as well?

**Comment by nocnokneo** [comment]
Yes, my coworkers have this camera and I am one of the few remote workers
needing to call into the mother ship.

I just want the remote PTZ ability. We use Cisco's Webex Connect for video
calls. Let me know if there is anything I can do, though I'm mostly a
Linux/C++ guy (actually the only use I have for my Windows machine is
making Webex video calls...)

On Sat, Jul 21, 2012 at 4:52 PM, Scott Hanselman <
reply@reply.github.com

**Comment by shanselman** [comment]
I'll make you a build next week to try out (email me) and you can use my existing relay. You're my new beta tester. ;)

## 

Scott Hanselman

**Comment by nocnokneo** [comment]
Great. Thanks. For initial testing the camera will be plugged into a
remotely located 32-bit Windows 7 machine. I see there's a jQuery web
interface so I shouldn't need to install anything on my end, right? (I've
got a Windows XP box)

On Sat, Jul 21, 2012 at 6:53 PM, Scott Hanselman <
reply@reply.github.com

**Comment by shanselman** [comment]
Depends. There's a number of options. Run a webserver on the camera machine and connect to it. You will need VPN and direct connection to the machine.

Or, use my buttons and controller and route around VPN with a relay.

## 

Scott Hanselman

**Comment by nocnokneo** [comment]
For my use case, I'm actually inside the firewall - just a satellite office
connecting to the camera machine at another office. Still, within the
company firewall they block certain ports on certain subnets. As long as
the listener port number is configurable it shouldn't be a problem.

However, the relay could still be useful for controlling the camera from a
handheld device (which aren't always possible to connect to the internal
wifi network). Especially if the webserver has user agent detection that
automatically serves a special version to mobile devices (using a
javascript accelerometer interface like
thishttp://www.albertosarullo.com/blog/javascript-accelerometer-demo-sourceto
control the PTZ would be sweet)

On Sat, Jul 21, 2012 at 7:51 PM, Scott Hanselman <
reply@reply.github.com

**Comment by nocnokneo** [comment]
Just checking in to see if you've had a chance to look at this. I'll be
physically at the location of the Logitech camera starting 9/25.

**Comment by shanselman** [comment]
It's just HTTP or HTTPS. There's no listener ports or ports to block. If you can web browse it will work.

## 

Scott Hanselman

**Comment by nocnokneo** [comment]
Sorry, I was referring the installer package. I be happy to test it if you
post one :-)

**Comment by shanselman** [comment]
I don't have an installer but I made this ZIP file to start playing. https://github.com/shanselman/PanTiltZoomSystem/downloads

**Comment by nocnokneo** [comment]
Thanks! My coworker (who is running Windows 7) was able to successfully run the ConsoleTester then RemoteCameraListener and the Buttons app (all locally on the camera machine). At first the camera was not responding to tilt/zoom commands, only pan commands. But after hitting the physical tilt button on the camera it started responding to commands from both ConsoleTester and RemoteCameraListener;

I wasn't able to test it remotely because I get an error dialog saying that "PTZRemoteLyncOverlay.exe is not a valid Win32 application". I have a 32-bit Windows XP machine - do I need Windows 7?

Also, we do not need to traverse a HTTP-only firewall. How do we change the configuration to use a direct connection to the PTZRemoteCameraListener? 

Is the Javascript web interface part of this build? If so, how do we configure and use it?

Thanks again.

**Comment by shanselman** [comment]
I have never tested on WinXP. Make sure DirectX is installed. No idea if it
will work. Likely not.

There is no direct connection choice. You'd have to change the code
yourself.

Yes, the JS interface is in the repo, but not in the ZIP. You are welcome
to it.

On Tue, Oct 30, 2012 at 1:30 PM, Taylor Braun-Jones <
notifications@github.com> wrote:

> Thanks! My coworker (who is running Windows 7) was able to successfully
> run the ConsoleTester then RemoteCameraListener and the Buttons app (all
> locally on the camera machine). At first the camera was not responding to
> tilt/zoom commands, only pan commands. But after hitting the physical tilt
> button on the camera it started responding to commands from both
> ConsoleTester and RemoteCameraListener;
> 
> I wasn't able to test it remotely because I get an error dialog saying
> that "PTZRemoteLyncOverlay.exe is not a valid Win32 application". I have a
> 32-bit Windows XP machine - do I need Windows 7?
> 
> Also, we do not need to traverse a HTTP-only firewall. How do we change
> the configuration to use a direct connection to the
> PTZRemoteCameraListener?
> 
> Is the Javascript web interface part of this build? If so, how do we
> configure and use it?
> 
> Thanks again.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shanselman/PanTiltZoomSystem/issues/1#issuecomment-9921591.

## 

Scott Hanselman
Help me? http://hnsl.mn/fightdiabetes
